### ISSUE TITLE
Port entity locking feature from LWCEntityLocking fork.

### ISSUE THREAD

**Issue by mibby** [pop4959/LWCX#193]
**LWC Version (/lwc admin version):** 2.2.8-dev-70d605a (Dev 90 https://ci.codemc.io/view/All/job/pop4959/job/LWCX-dev/90/)
**Server version (/version):** Purpur dev 1612 (git-Purpur-1612) (Paper 1.18.2)

**Short five word summary of issue:** 
Entities such as armor stands and item frames cannot be locked.

**Detailed description of problem:**
I am migrating from the LWCEntityLocking fork by Brokkonaut.
https://github.com/Brokkonaut/LWCEntityLocking

This fork contains functionality for locking entities such as armor stands, item frames, paintings, chest minecarts, normal mobs, etc. It handles configuration similar to block locking with new sections under the protections config section.

i.e.
```
protections:
    entities:
        armor_stand:
            enabled: true
        painting:
            enabled: true
        item_frame:
            enabled: true
        chest_minecart:
            enabled: true
    special:
        noaimob:
            enabled: false
```

Adding these items to LWCX's protection config does not allow locking of the items.
```
    blocks:
        armor_stand:
            enabled: true
        painting:
            enabled: true
        item_frame:
            enabled: true
        chest_minecart:
            enabled: true
```

Would it be possible to pull in changes from that fork to allow locking of those entity types? It is licensed under BSD 2-Clause which allows modification and redistribution. My players relied heavily on being able to lock armor stands and item frames. The implementation in that fork worked relatively fine and bug free. The reason for migrating to LWCX was for the addon support & custom features such as ``/cdisplay`` for lecterns.
