### ISSUE TITLE
Explosions Don't Destroy Chests

### ISSUE THREAD

**Issue by ArifErdoganK** [pop4959/LWCX#44]
**LWC Version (/lwc admin version):**
1.9.7
**Server version (/version):**
1.8

**Short five word summary of issue:**
Explosions Don't Destroy Chests

**Detailed description of problem:**
Explosion settings in core.yaml do not work. With the locked chest, the blocks around it don't explode this only happens if the chest is locked. Tested on a server not plugin.

**Comment by pop4959** [comment]
I'm not sure I understand your question. If you want to be able to use explosives on protected blocks there is a setting for that. I'm not able to reproduce this issue. Please provide your full configuration if you would like me to test it. Also make sure that if you have changed any settings, you are not using something like /reload or plugman, which will break most plugins including LWC.

**Comment by ArifErdoganK** [comment]
Problem i mentioned is in video below. Only LWC is installed.
[](https://vimeo.com/360408801)

**core.yaml**
```
protections:
    denyRedstone: false
    denyHoppers: false
    autoRegister: false
    ignoreBlockDestruction: false
    ignoreLeftClick: false
    ignoreRightClick: false
    ignoreExplosions: false
    allowEntityBreakDoor: false
    allowEntityInteract: false
    quiet: false
    readonly-modify: false
    readonly-remove: false
    blocks:
        chest:
            enabled: true
```
